### ISSUE TITLE
MySql TIMESTAMP returns null

### ISSUE THREAD

**Issue by simmslabs** [tauri-apps/tauri-plugin-sql#87]
MySql TIMESTAMP returns null

**Comment by FabianLars** [comment]
We only really support a small-ish subset of data types, mainly focused on sqlite, which we consider the main use case, especially since 99% of the times actual sql servers should be behind some kind of api server and not directly accessed from clients...

That said, another PR added `DATETIME` support so maybe you can use this instead (although tbh i'm thinking about removing it again 🤔)

Going to close this for now unless @lucasfernog thinks this is indeed in scope (if it is, we should think about other datatypes too)
